FROM node:23-slim AS builder
WORKDIR /usr/src/app
COPY ./notes/package.json .
COPY ./notes/package-lock.json* .
RUN npm ci

FROM node:23-slim
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/ /usr/src/app/
COPY ./notes ./
CMD ["npx", "quartz", "build", "--serve"]
