name: Build and push notes image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "notes/**/*.*"
      - "docker/Dockerfile.notes"
      - ".github/workflows/notes-image.yaml"

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.CONTAINER_REGISTRY }}/homelab/notes
          tags: |
            type=raw,value=latest

      - name: Login ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.CONTAINER_REGISTRY }}
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./docker/Dockerfile.notes
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
